# Assignment 8

## Shealyn Arthur

## Version 1 

#



#### 1.

In [1]:
import numpy as np

In [4]:
list1=[10,20,30,40]
array1=np.array(list1)
array1

array([10, 20, 30, 40])

In [7]:
array1.resize((2,2))

In [8]:
array1

array([[10, 20],
       [30, 40]])

#### (a)

In [9]:
array1**2

array([[ 100,  400],
       [ 900, 1600]], dtype=int32)

#### (b)

In [10]:
array1+100

array([[110, 120],
       [130, 140]])

#### (c)

In [11]:
array1*5

array([[ 50, 100],
       [150, 200]])

#### (d)

In [15]:
np.sqrt(array1)

array([[3.16227766, 4.47213595],
       [5.47722558, 6.32455532]])

#### 2.

In [21]:
array2=np.arange(3,28,3)
array2.resize(3,3)
array2

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [23]:
array3=np.linspace(10,20,9)
array3.resize(3,3)
array3

array([[10.  , 11.25, 12.5 ],
       [13.75, 15.  , 16.25],
       [17.5 , 18.75, 20.  ]])

In [25]:
array4=array2*array3
array4

array([[ 30. ,  67.5, 112.5],
       [165. , 225. , 292.5],
       [367.5, 450. , 540. ]])

#### 3. 

In [34]:
x1=np.load('process1.npy')
x2=np.load('process2.npy')
x3=np.load('process3.npy')
x4=np.load('process4.npy')
x5=np.load('process5.npy')

In [36]:
array5=np.concatenate([x1,x2,x3,x4,x5])
array5

array([[52, 12, 81,  0, 58],
       [96,  4, 61, 16, 43],
       [38, 96, 45, 17, 58],
       [97, 21, 22, 25,  6],
       [77,  6, 19,  2, 74]])

In [47]:
c1=array5[:,0]
c2=array5[:,1]
c3=array5[:,2]
c4=array5[:,3]
c5=array5[:,4]

In [49]:
print("Column 1 Mean: ", c1.mean())
print("Column 2 Mean: ", c2.mean())
print("Column 3 Mean: ", c3.mean())
print("Column 4 Mean: ", c4.mean())
print("Column 5 Mean: ", c5.mean())

Column 1 Mean:  72.0
Column 2 Mean:  27.8
Column 3 Mean:  45.6
Column 4 Mean:  12.0
Column 5 Mean:  47.8
